# Generated by Django 3.1 on 2020-08-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('classnote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code', to='classnote.pswd'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='user_profile',
            field=models.ManyToManyField(to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='pswd',
            name='passcode',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
