# Generated by Django 3.1 on 2020-08-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classnote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classname',
            field=models.CharField(default='dskjglfkldsfjkg', max_length=50),
            preserve_default=False,
        ),
    ]
