# Generated by Django 3.1 on 2020-08-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classnote', '0002_auto_20200812_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='identifier',
            field=models.CharField(default='adsflkn', max_length=6),
            preserve_default=False,
        ),
    ]
