# Generated by Django 3.1 on 2020-08-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classnote', '0002_auto_20200813_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='code',
        ),
        migrations.AddField(
            model_name='classroom',
            name='passcode',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
