# Generated by Django 3.1 on 2020-08-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classnote', '0003_classroom_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
