# Generated by Django 3.1 on 2020-08-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classnote', '0003_auto_20200813_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pswd',
        ),
    ]
