# Generated by Django 3.1 on 2020-08-13 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classnote', '0004_delete_pswd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pswd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='passcode',
        ),
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code', to='classnote.pswd'),
        ),
    ]
