# Generated by Django 3.0.7 on 2020-08-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classnote', '0007_auto_20200813_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='passwd', max_length=6),
        ),
        migrations.DeleteModel(
            name='Pswd',
        ),
    ]
