# Generated by Django 3.0.6 on 2020-06-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passcode',
            new_name='Pswd',
        ),
    ]
