# Generated by Django 3.0.7 on 2020-07-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_auto_20200625_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pswd',
            name='passcode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=50, null=True)),
                ('passcod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='class.Pswd')),
            ],
        ),
    ]
