# Generated by Django 3.0.7 on 2020-07-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0006_auto_20200718_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='user',
        ),
    ]
