# Generated by Django 3.0.7 on 2020-07-19 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class', '0007_remove_classroom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='user',
            field=models.OneToOneField(default='noob', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
